<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-14T12:06:26 PKT" name="Suite" finished-at="2023-11-14T12:07:12 PKT" duration-ms="46471">
    <groups>
    </groups>
    <test started-at="2023-11-14T12:06:26 PKT" name="Error Validation Test" finished-at="2023-11-14T12:07:01 PKT" duration-ms="35074">
      <class name="appiumTest.appiumFrameworkTest.FormErrorValidation">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:appiumTest.appiumFrameworkTest.FormErrorValidation@478db956]" started-at="2023-11-14T12:06:26 PKT" name="ConfigureAppium" finished-at="2023-11-14T12:06:31 PKT" duration-ms="5343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method signature="fillForm()[pri:0, instance:appiumTest.appiumFrameworkTest.FormErrorValidation@478db956]" started-at="2023-11-14T12:06:31 PKT" name="fillForm" finished-at="2023-11-14T12:07:01 PKT" duration-ms="29194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillForm -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:appiumTest.appiumFrameworkTest.FormErrorValidation@478db956]" started-at="2023-11-14T12:07:01 PKT" name="tearDown" finished-at="2023-11-14T12:07:01 PKT" duration-ms="503" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- appiumTest.appiumFrameworkTest.FormErrorValidation -->
    </test> <!-- Error Validation Test -->
    <test started-at="2023-11-14T12:07:02 PKT" name="EndToEndTest" finished-at="2023-11-14T12:07:12 PKT" duration-ms="10911">
      <class name="appiumTest.appiumFrameworkTest.FormEcomeEndToEndTest">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:appiumTest.appiumFrameworkTest.FormEcomeEndToEndTest@6aa8e115]" started-at="2023-11-14T12:07:02 PKT" name="ConfigureAppium" finished-at="2023-11-14T12:07:06 PKT" duration-ms="4951" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method signature="fillForm()[pri:0, instance:appiumTest.appiumFrameworkTest.FormEcomeEndToEndTest@6aa8e115]" started-at="2023-11-14T12:07:06 PKT" name="fillForm" finished-at="2023-11-14T12:07:11 PKT" duration-ms="4363" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at appiumTest.appiumFrameworkTest.FormEcomeEndToEndTest.fillForm(FormEcomeEndToEndTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillForm -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:appiumTest.appiumFrameworkTest.FormEcomeEndToEndTest@6aa8e115]" started-at="2023-11-14T12:07:12 PKT" name="tearDown" finished-at="2023-11-14T12:07:12 PKT" duration-ms="406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- appiumTest.appiumFrameworkTest.FormEcomeEndToEndTest -->
    </test> <!-- EndToEndTest -->
  </suite> <!-- Suite -->
</testng-results>
